### ISSUE TITLE
Throttle upload-salt-reports

### ISSUE THREAD

**Issue by bwellsnc** [theforeman/smart_proxy_salt#25]
I am using salt in combination with katello 3.2.  I am wondering is there a way to throttle upload-salt-reports.   I am seeing a problem when I am running this.  It is causing my machine to utilize 100% cpu and cause memory to spike from 4gb to 13gb.  It appears to be a problem with passenger, but I have done as much as I can to tune passenger.  I have the report upload running every 10 minutes, so every 10 minutes it spikes.   I need a way to batch the reports if possible, 20 to 30 at a time.  Thanks!

**Comment by sbernhard** [comment]
Better implementation. See https://github.com/theforeman/smart_proxy_salt/pull/39
