### ISSUE TITLE
Suggestion: Bulk change of Salt-Master

### ISSUE THREAD

**Issue by nodermatt** [theforeman/smart_proxy_salt#32]
It'd be great to have a bulk change action to change the Salt Master of multiple hosts at once.

The salt-master is not set automatically when salt smart-proxy plugin creates a new host entry or atleast it didn't for me. Therefore you have to manually set the salt-master for each host. With growing host count that is quite a lot of work.

Theres an option to bulk change the monitoring proxy for example. I am not fluent in Ruby but I am familiar with how web applications handle requests and return views. If you guys could point me to the relevant components I need to analyze, I'd try giving it a shot to fork and pull request.

![image](https://user-images.githubusercontent.com/1467464/47437650-53ca1e80-d7a9-11e8-9ed2-08466524eebf.png)

**Comment by sbernhard** [comment]
I guess, this needs to be a feature of https://github.com/theforeman/foreman_salt Please reopen this issue at this project.

**Comment by nodermatt** [comment]
@sbernhard Thanks for the input. I seem not to be able to create issues on that project. How can I file a ticket?

**Comment by sbernhard** [comment]
https://projects.theforeman.org/projects/salt

**Comment by nodermatt** [comment]
@sbernhard Awesome, thanks for the pointer! (+1)

**Comment by sbernhard** [comment]
See https://github.com/theforeman/foreman_salt/pull/92 - would be great if you can test it.

**Comment by nodermatt** [comment]
@sbernhard Wow, thanks for the initiative!
Forgive me, I am fairly new to ruby development: How can I apply your patch to my installed smart_proxy gem? I found instructions on [SO](https://stackoverflow.com/questions/930126/how-do-you-apply-a-patch-to-ruby-on-rails) but I can't find the gem file - only the gemspec which only contains dependencies, author information, etc.

Using ruby list and grep I was able to determine the following path

```
support@server0141:~$ gem list -d | grep -B 3 -A 4 salt

    Classy web-development dressed in a DSL

smart_proxy_salt (2.1.9)
    Authors: Michael Moll, Stephen Benjamin
    Homepage: https://github.com/theforeman/smart_proxy_salt
    License: GPLv3
    Installed at: /usr/share/rubygems-integration/all

    SaltStack Plug-In for Foreman's Smart Proxy

```
Here are all the gemspecs, but no gem files.

```
support@server0141:~$ ls -la /usr/share/rubygems-integration/all/specifications/
total 152
drwxr-xr-x 2 root root 4096 Nov 14 06:22 .
drwxr-xr-x 3 root root 4096 Aug 21  2018 ..
-rw-r--r-- 1 root root 9986 Mar 13  2016 bundler-1.11.2.gemspec
-rw-r--r-- 1 root root 2108 May 26  2016 bundler_ext-0.4.1.gemspec
-rw-r--r-- 1 root root 1101 Jan 11  2016 concurrent-ruby-1.0.0.gemspec
-rw-r--r-- 1 root root 1217 Jul 24  2015 deep_merge-1.0.1.gemspec
-rw-r--r-- 1 root root 3562 Mar 13  2016 did_you_mean-1.0.0.gemspec
-rw-r--r-- 1 root root 1833 Sep  9  2015 gssapi-1.2.0.gemspec
-rw-r--r-- 1 root root 2854 Sep  9  2015 hiera-2.0.0.gemspec
-rw-r--r-- 1 root root 5204 Mar 13  2016 minitest-5.8.4.gemspec
-rw-r--r-- 1 root root 1866 Mar 13  2016 molinillo-0.4.3.gemspec
-rw-r--r-- 1 root root 3608 Jan  6  2016 net-http-persistent-2.9.4.gemspec
-rw-r--r-- 1 root root 1316 Mar 13  2016 net-telnet-0.1.1.gemspec
-rw-r--r-- 1 root root 1759 Mar 13  2016 power_assert-0.2.7.gemspec
-rw-r--r-- 1 root root 7904 Mar 10  2016 rack-1.6.4.gemspec
-rw-r--r-- 1 root root 3450 Nov  9 17:37 rack-protection-1.5.3.gemspec
-rw-r--r-- 1 root root 8562 Mar 13  2016 rake-10.5.0.gemspec
-rw-r--r-- 1 root root 1390 Mar 13  2016 rb-inotify-0.9.7.gemspec
-rw-r--r-- 1 root root 8044 May  6  2015 rgen-0.7.0.gemspec
-rw-r--r-- 1 root root 1417 Oct 22  2017 rsec-0.4.2.gemspec
-rw-r--r-- 1 root root 5245 Apr 28  2016 rubyipmi-0.10.0.gemspec
-rw-r--r-- 1 root root 2763 Sep  9  2015 safe_yaml-1.0.4.gemspec
-rw-r--r-- 1 root root 5846 Mar 13  2016 sinatra-1.4.7.gemspec
-rw-r--r-- 1 root root 1199 May  7  2018 smart_proxy_salt-2.1.9.gemspec
-rw-r--r-- 1 root root 6192 Mar 13  2016 test-unit-3.1.7.gemspec
-rw-r--r-- 1 root root 6521 Aug 19  2015 thor-0.19.1.gemspec
-rw-r--r-- 1 root root 3935 Jan 13  2016 tilt-2.0.1.gemspec
```

**Comment by sbernhard** [comment]
The PR needs to be applied on foreman directly. 
You can do it like https://help.github.com/en/articles/checking-out-pull-requests-locally

or you can get the patch and apply it, see:
https://patch-diff.githubusercontent.com/raw/theforeman/foreman_salt/pull/92.patch

Apply the patch with "patch" or "git am"
