### ISSUE TITLE
Salt Compatibility with Foreman 1.20

### ISSUE THREAD

**Issue by nodermatt** [theforeman/smart_proxy_salt#33]
Hi guys,

I'm planning to upgrade my Foreman 1.18 instance to 1.20 but i wanted to make sure that Salt is still supported with the current version. As there were no indications in the 1.20 release notes I'd assume it will still work. Nevertheless, I think it'd be great to update the [Salt plugin doc](https://theforeman.org/plugins/foreman_salt/7.0/index.html) as they stop listing support at Foreman 1.13.X with smart proxy 2.X.

Maybe a table like the foreman_salt repo would be a good fit to indicate anything above 1.13 is fine:
![image](https://user-images.githubusercontent.com/1467464/52058323-7ff2f980-2567-11e9-96eb-cce64c30a6df.png)
source https://github.com/theforeman/foreman_salt

**Comment by sbernhard** [comment]
It should work. Feel free to open a issue if something is not broken. Create a PR to update the foreman/ salt plugin matrix.
