### ISSUE TITLE
Unable to install ruby-smart-proxy-salt on Ubuntu 20.04

### ISSUE THREAD

**Issue by L4rS6** [theforeman/smart_proxy_salt#77]
Due to wrong package dependencies I'm unable to install the `ruby-smart-proxy-salt`  package:

```
# apt install ruby-smart-proxy-salt
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ruby-smart-proxy-salt : Depends: ruby-smart-proxy-salt-core (>= 0.0.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Ubuntu Version:
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

Foreman sources:
```
deb http://deb.theforeman.org focal 3.1
deb http://deb.theforeman.org plugins 3.1
```

I already reported it here, but there was no response to it: https://projects.theforeman.org/issues/33994

Thank you in advance and let me know if there are more details needed.

**Comment by L4rS6** [comment]
Where do I have to place this that somebody will have a look into it?

**Comment by nadjaheitmann** [comment]
@L4rS6 Looks like a package for Debian is missing. I think you have already put the issue in all relevant place, thanks for reporting!

**Comment by sbernhard** [comment]
I'm sorry. The 3.1 debian packages for salt were missing. Created 2 pull requests to build them. But I actually don't know when they are available.

https://github.com/theforeman/foreman-packaging/pull/7546
https://github.com/theforeman/foreman-packaging/pull/7545

Maybe you can have a look at https://deb.theforeman.org/pool/plugins/nightly/ - use at your own risk.

**Comment by L4rS6** [comment]
Thank you @sbernhard

**Comment by L4rS6** [comment]
I was able to install and update the latest packages without any dependency problems.
