### ISSUE TITLE
Salt report upload broken with PyYaml versions shipped with salt onedir packages

### ISSUE THREAD

**Issue by gkulyk** [theforeman/smart_proxy_salt#88]
Recent salt versions are available as onedir packages only (see [https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#upgrade-to-onedir](https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#upgrade-to-onedir)), here by default the current version of PyYAML 6.0.1 is shipped. While PyYaml versions 5.x already deprecated the `yaml.load(input)` function call (see [https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation)), 6.x removed it.

smart_proxy_salt uses the function call in 3 places:

- /salt/minion_auth/srv/salt/_runners/foreman_https.py
- /salt/report_upload/srv/salt/_runners/foreman_report_upload.py
- /sbin/upload-salt-reports

A straightforward fix would be, to replace the `yaml.load(f.read())` calls with `yaml.load(f.read(), Loader=yaml.FullLoader)` ones, this was the default behavior for PyYaml 5.x. For security reasons it might be also desirable to check if a switch to the `yaml.SafeLoader` is feasable.

**Comment by nadjaheitmann** [comment]
Closed via #89
